# SPDX-FileCopyrightText: 2025 Digg - Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0

name: Release Dev Workflow

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  # Build Android app with signing
  build:
    uses: diggsweden/reusable-ci/.github/workflows/build-gradle-app.yml@c05880c429c91786427337cf06853c041d1f729f # v2.7.4
    permissions:
      contents: read
    secrets: inherit
    with:
      reusable-ci-ref: v2.7.3
      java-version: "21"
      build-module: "app"
      gradle-tasks: "assembleDemoRelease bundleDemoRelease"
      enable-signing: true
      artifact-name: "wallet-android-demo"

  # Publish to Google Play internal track
  publish-google-play:
    needs: build
    uses: diggsweden/reusable-ci/.github/workflows/publish-google-play.yml@c05880c429c91786427337cf06853c041d1f729f # v2.7.4
    permissions:
      contents: read
    secrets: inherit
    with:
      reusable-ci-ref: v2.7.3
      aab-artifact-name: "wallet-android-demo"
      package-name: "se.digg.wallet.demo"
      track: "internal"
      status: "completed"
