# SPDX-FileCopyrightText: 2025 Digg - Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0

name: Release Dev Workflow

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  # Build Android app with signing
  build:
    uses: diggsweden/reusable-ci/.github/workflows/build-gradle-android.yml@a51c0edbdb0799550d4293863edfc4d8f1643742 # test feat/build-sbom-enhanced
    permissions:
      contents: read
    secrets: inherit
    with:
      reusable-ci-ref: a51c0edbdb0799550d4293863edfc4d8f1643742
      java-version: "21"
      build-module: "app"
      product-flavor: "demo"
      build-types: "release"
      include-aab: true
      enable-signing: true
      artifact-name-prefix: "wallet-android-demo"

  # Publish to Google Play internal track
  publish-google-play:
    needs: build
    uses: diggsweden/reusable-ci/.github/workflows/publish-google-play.yml@a51c0edbdb0799550d4293863edfc4d8f1643742 # test feat/build-sbom-enhanced
    permissions:
      contents: read
    secrets: inherit
    with:
      reusable-ci-ref: a51c0edbdb0799550d4293863edfc4d8f1643742
      aab-artifact-name: ${{ needs.build.outputs.aab-name }}
      package-name: "se.digg.wallet.demo"
      track: "internal"
      status: "completed"
