# SPDX-FileCopyrightText: 2025 Digg - Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0

name: Gradle Test

on: [workflow_call] # yamllint disable-line rule:truthy

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: ['21']
        os: [ubuntu-latest]

    permissions:
      contents: read
      packages: read

    steps:
      - name: Harden GitHub runner
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@cf277c60eb25467037889841efdb72551f06f6c3 # v4.9.1
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin' # Popular Java distribution
          cache: 'gradle' # Enables Gradle caching

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Decode secrets.properties
        run: printf '%s' "${{ secrets.SECRETS_PROPERTIES_BASE64 }}" | base64 --decode > secrets.properties

      - name: Log working dir
        run: ls -al

      - name: Run tests
        run: "# shellcheck disable=SC2086 \n./gradlew test\n"
